/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 ./public/warped blue ball.glb
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Ball(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/warped blue ball.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Cheese.reset().fadeIn(0.5).play();
    console.log(actions.Cheese);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Empty"
          position={[0, 1, 2.56]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <group
          name="BezierCircle"
          position={[0, 1, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials['Material.001']}
          position={[0, 1, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/warped blue ball.glb');
