/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/hello.glb
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/all';
gsap.registerPlugin(ScrollTrigger);

export function Hello(props) {
  const { nodes, materials } = useGLTF('/hello.glb');
  const helloMesh = useRef();
  const tl = gsap.timeline();
  useEffect(() => {
    tl.to(helloMesh.current.position, {
      z: 0,

      scrollTrigger: {
        scrub: 1,
      },
    });
    tl.to(helloMesh.current.position, {
      y: 40,

      scrollTrigger: {
        scrub: 1,
      },
    });
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={helloMesh}
        geometry={nodes.Text.geometry}
        material={materials['Material.001']}
        position={[0, 0, -20]}
        scale={3}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/hello.glb');
